INSERT  INTO COM_FINVI_OASIS_RESTRICTIONS_{PP_TenantName}.CEASE_RESTRICTIONS
(
	CEASE_ALL,
	CEASE_CALLS,
	CEASE_LETTERS,
	TYPE,
	ENTITY_ID,
	ENTITY_TYPE,
	UUID,
	CREATED_ON,
	MODIFIED_ON,
	CREATED_BY,
	MODIFIED_BY,
	SOURCE
)
SELECT 
	CEASE_ALL,
	CEASE_CALLS,
	CEASE_LETTERS,
	RS.TYPE,
	RP.UUID   ENTITY_ID,
	ENTITY_TYPE, 
	SYS_GUID()  AS UUID,
	SYSDATE AS CREATED_ON,
	SYSDATE AS MODIFIED_ON,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATED_BY,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIED_BY,		
	 CS.id  AS SOURCE	
FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_RESTRICTION RS
	JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNT A ON RS.ACCOUNT_ID = A.MIGRATION_SOURCE_ID
	JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER C ON RS.CONSUMER_ID = C.MIGRATION_SOURCE_ID
	JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLEINDEX RI ON RI.CUSTOMERINFOID  = c.CUSTOMERID
	JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLE RP ON Ri.RESPONSIBLEID = RP.RESPONSIBLEID AND RP.ACCOUNTNUM = A.ACCOUNTNUM
	JOIN COM_FINVI_OASIS_STATIC_DATA_{PP_TenantName}.CONSENT_SOURCE cs ON RS."SOURCE" =cs.NAME 