INSERT INTO COM_FINVI_OASIS_RESTRICTIONS_{PP_TenantName}.COMMUNICATION_RESTRICTION
(
	CUSTOMER_ID,
	COMMUNICATION_TYPE,
	ENTITY_ID,
	IS_COMPLETE_RESTRICTION,
	UUID,
	CREATED_ON,	
	MODIFIED_ON,
	CREATED_BY,
	MODIFIED_BY,
	PHONE_NUM
)
SELECT 
	C.UUID AS CUSTOMER_ID,
	COMMUNICATION_TYPE,	
	c2.UUID  ENTITY_ID, 
	IS_COMPLETE_RESTRICTION,
	SYS_GUID() AS UUID,
	SYSDATE AS CREATED_ON,
	SYSDATE AS MODIFIED_ON,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATED_BY,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIED_BY,	
	RS.PHONE_NUM
FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_RESTRICTION RS 
	JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER C ON RS.CONSUMER_ID = C.MIGRATION_SOURCE_ID
	JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMERCONTACTPHONE c2   ON c.CUSTOMERID  = C2.CUSTOMERID  
	AND rs.PHONE_NUM = c2.PHONENUM 