INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CALLWRAPUPS 
(
	ID,
	CUSTOMERID,
	NOTESID,
	CALLMETHOD,
	PHONENUMBER,
	CALLOUTCOME,
	CREATEDAT,
	UPDATEDAT,
	CREATEDBY,	
	UPDATEDBY,
	SPOKETOOPTION,
	IS_OVERDUE,
	CALL_OUTCOME_METHOD_REFID
)
SELECT 
	CALLWRAPUPID,
	CH.CONSUMER_ID  AS CUSTOMER_ID,
	NOTESID,
	Ch.CALLMETHOD,
	SUBSTR(REPLACE(REPLACE(REPLACE(CH.PHONENUMBER,'-',''),'(',''),')',''),1,10) PHONENUMBER,
	CH.CALLOUTCOME,
	SYSDATE AS CREATEDAT,
	SYSDATE AS UPDATEDAT,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATEDBY,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS UPDATEDBY,		
	CH.SPOKETOOPTION,
	CH.IS_OVERDUE,
	cwum.CALL_OUTCOME_METHOD_REFID
FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_WRK_STG_CALL_HISTORY CH
	LEFT JOIN COM_FINVI_OASIS_STATIC_DATA_{PP_TenantName}.CALL_METHOD SCM ON SCM.CODE = Ch.CALLMETHOD
	LEFT JOIN COM_FINVI_OASIS_STATIC_DATA_{PP_TenantName}.CALL_WRAP_UP sscwu  ON sscwu.CODE = CH.CALLOUTCOME
	LEFT JOIN 
		(
			SELECT 
				HEXTORAW(REPLACE(CALL_METHOD_ID, '-', '')) CALL_METHOD_ID
				,HEXTORAW(REPLACE(CALL_WRAPUP_ID , '-', ''))CALL_WRAPUP_ID
				,ID AS CALL_OUTCOME_METHOD_REFID
			FROM COM_FINVI_OASIS_STATIC_DATA_{PP_TenantName}.CALL_WRAP_UP_METHOD
		) cwum ON SCM.ID = CALL_METHOD_ID AND sscwu.id=CALL_WRAPUP_ID 
WHERE SUBSTR(REPLACE(REPLACE(REPLACE(CH.PHONENUMBER,'-',''),'(',''),')',''),1,10) IS NOT NULL