INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.NOTES 
(
	ID,
	CONTENT,
	TYPE,
	CREATEDAT,
	UPDATEDAT,
	CREATEDBY,
	UPDATEDBY,
	MIG_SRC_ACCT_ID,
	MIG_SRC_CONS_ID
)
SELECT 
	NOTESID AS ID,
	COALESCE(NOTES,'Migrated Call History') AS CONTENT,
	NOTES_TYPE AS TYPE,
	SYSDATE AS CREATEDAT,
	SYSDATE AS UPDATEDAT,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATEDBY,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS UPDATEDBY,		
	A.MIGRATION_SOURCE_ID  AS MIG_SRC_ACCT_ID,
	C.MIGRATION_SOURCE_ID  AS MIG_SRC_CONS_ID
FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_WRK_STG_CALL_HISTORY WCH
JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER C ON WCH.CONSUMER_ID = C.CUSTOMERID 
JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNT A ON WCH.ACCOUNT_ID = A.ACCOUNTNUM   
WHERE SUBSTR(REPLACE(REPLACE(REPLACE(WCH.PHONENUMBER,'-',''),'(',''),')',''),1,10) IS NOT NULL