INSERT INTO COM_FINVI_OASIS_RESTRICTIONS_{PP_TenantName}.DIALER_COUNTER
(
	CREATED_ON,
	MODIFIED_ON,
	ATTEMPT_DATE,
	CALL_ATTEMPT,
	CALL_OVERRIDE,
	CALLBACK_REQUEST,
	RPC_CONTACT,
	MISDIRECTED_CALL,
	PHONE_NUM,
	DIALER_RESULT_ID
)
SELECT 
	CREATED_ON,
	MODIFIED_ON,
	ATTEMPT_DATE + 0.5 AS ATTEMPT_DATE,
	CALL_ATTEMPT,
	CALL_OVERRIDE,
	CALLBACK_REQUEST,
	RPC_CONTACT,
	MISDIRECTED_CALL,
	SUBSTR(REPLACE(REPLACE(REPLACE(WCH.PHONENUMBER,'-',''),'(',''),')',''),1,10) PHONE_NUM
	,DIALER_RESULT_ID
FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_WRK_CALLHIST_DIALER_COUNTER WCH