INSERT INTO ETL_OASIS_DATA_MIG_{PP_TenantName}.WRK_ACCOUNT_HIST
(
	CATEGORY,
	TYPE,
	CONTEXT,
	ACCOUNT_UUID,
	CUSTOMER_UUID,
	ACTIVITY_ID,
	TRANSACTION_ID,
	ACTIVITY_DATE
)
SELECT 
	AH.CATEGORY 
	,AH."TYPE" 
	,WC.CONTEXT 
	,CASE WHEN  
		WC.CONTEXT   IN ('ACCOUNT_HOLDER', 'ACCOUNT_HOLDER_SET') OR WC.CONTEXT IS NULL
		THEN LOWER
				(
					SUBSTR(a.UUID,1,8) || '-' ||
					SUBSTR(a.UUID,9,4) || '-' ||
					SUBSTR(a.UUID,13,4) || '-' ||
					SUBSTR(a.UUID,17,4) || '-' ||
					SUBSTR(a.UUID,21)
				)  
		ELSE NULL 
	END AS ACCOUNT_UUID
	,CASE WHEN  
		CONTEXT  IN  ('CONSUMER') 
		THEN LOWER
				(
					SUBSTR(C.UUID,1,8) || '-' ||
					SUBSTR(c.UUID,9,4) || '-' ||
					SUBSTR(c.UUID,13,4) || '-' ||
					SUBSTR(c.UUID,17,4) || '-' ||
					SUBSTR(c.UUID,21)
				)  
		ELSE NULL
	END AS CONSUMER_UUID
	,SYS_GUID() AS ID
	,SYS_GUID() AS TRANSACTION_ID
	,COALESCE(Ah.ACTIVITY_DATE, TO_DATE('1950-12-31','yyyy-mm-dd'))
FROM ETL_STG_ACTVT_HIST AH
	INNER JOIN 
	( 
		SELECT 
			MIGRATION_SOURCE_ID , 
			RAWTOHEX(a1.UUID)  UUID
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNT a1 
	) A ON A.MIGRATION_SOURCE_ID = AH.ACCOUNT_ID
	INNER JOIN 
	( 
		SELECT 
			MIGRATION_SOURCE_ID , 
			RAWTOHEX(a1.UUID)  UUID
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER a1  
	) C ON AH.CONSUMER_ID  = C.MIGRATION_SOURCE_ID
	LEFT JOIN WRK_CONTEXT WC ON WC."TYPE" = AH."TYPE" AND WC.CATEGORY = AH.CATEGORY   