INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CALLWRAPUPSACCOUNT
(
	ID,
	ACCOUNTNUM,
	CALLWRAPUPID,
	CREATEDAT,
	UPDATEDAT,
	CREATEDBY,
	UPDATEDBY
)
SELECT 
	CALLWRAPUP_ACC_ID,
	ACCOUNT_ID ,
	CALLWRAPUPID ,
	SYSDATE AS CREATEDAT,
	SYSDATE AS UPDATEDAT,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATEDBY,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS UPDATEDBY
FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_WRK_STG_CALL_HISTORY CH
 JOIN  COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CALLWRAPUPS CW ON CH.CALLWRAPUPID = CW.ID 