INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.DIALERAUDIT
            (BATCHID,
            CREATEDATE,
             LASTUPDATEDATE,
             BALANCE,
             CALLSECONDS,
             CAMPAIGNNUMBER,
             DEBTORNAME,
             DEBTORNAME2,
             STATUS,
             AGENTACTIONDESCRIPTION,
             PHONETYPE,
             AGENTACTIONCODE,
             PHONENUMBER,
             ACCOUNTNUM,
             RESPONSIBLEID,
             ADDR_LINE1,
             ADDR_LINE2,
             AGENT_CALL_TIME,
             AGENT_USER_ID,
             CALL_DATE_INITIATION,
             CALL_DISCONNECT_DATE,
             CALL_DISCONNECT_TIME,
             CALL_ID,
             CALL_TIME_INITIATION,
             CITY,
             CLIENT_REF_NUM,
             EMAIL_ADDR,
             ETL_LOAD_TS,
             FILE_NUMBER,
             PH_NUM2,
             PH_NUM3,
             PH_NUM4,
             PH_TYPE2,
             PH_TYPE3,
             PH_TYPE4,
             RAW_RESULT_CODE,
             RESULT_CODE,
             STATE,
             ZIP,
             CALL_METHOD,
             CALL_WRAPUP_ID,
             CREATED_BY,
			MODIFIED_BY)
SELECT CH.CAMPAIGNNUMBER AS BATCHID,
	   CURRENT_TIMESTAMP CREATEDATE,
       CURRENT_TIMESTAMP LASTUPDATEDATE,
       CH.BALANCE,
       CH.CALLSECONDS,
       CH.CAMPAIGNNUMBER,
       CH.DEBTORNAME,
       CH.DEBTORNAME2,
       CH.STATUS,
       CH.AGENTACTIONDESCRIPTION,
       CH.PHONETYPE,
       CH.AGENTACTIONCODE,
       SUBSTR(REPLACE(REPLACE(REPLACE(CH.PHONENUMBER,'-',''),'(',''),')',''),1,10) AS PHONENUMBER,
       CH.ACCOUNT_ID,
       RP.RESPONSIBLEID,
       ADDR_LINE1,
       ADDR_LINE2,
       AGENT_CALL_TIME,
       AGENT_USER_ID,
       CALL_DATE_INITIATION,
       CALL_DISCONNECT_DATE,
       CALL_DISCONNECT_TIME,
       CALL_ID,
       CALL_TIME_INITIATION,
       CITY,
       CLIENT_REF_NUM,
       EMAIL_ADDR,
       ETL_LOAD_TS,
       FILE_NUMBER,
       PH_NUM2,
       PH_NUM3,
       PH_NUM4,
       PH_TYPE2,
       PH_TYPE3,
       PH_TYPE4,
       RAW_RESULT_CODE,
       CH.AGENTACTIONCODE AS RESULT_CODE,
       STATE,
       ZIP,
       CH.CALLMETHOD,
       CH.CALLWRAPUPID,
       (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') CREATED_BY,
       (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') MODIFIED_BY
FROM   ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_WRK_STG_CALL_HISTORY CH
JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLE RP
  ON CH.ACCOUNT_ID = RP.ACCOUNTNUM