INSERT INTO COM_FINVI_OASIS_ACCOUNT_ACTIVITY_{PP_TenantName}.RELATED_ENTITY
(
	ID,
	ACTIVITY_ID,
	RELATED_ENTITY_ID,
	CREATED_ON,
	MODIFIED_ON
) 
SELECT  
	SYS_GUID() AS ID 
	,Activity_ID  AS ACTIVITY_ID
	,CASE WHEN ACCOUNT_UUID IS NULL THEN CUSTOMER_UUID ELSE ACCOUNT_UUID END AS RELATED_ENTITY_ID 
	, ACTIVITY_DATE + 0.5 AS CREATED_ON
	,SYSDATE  AS MODIFIED_ON 
FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.WRK_ACCOUNT_HIST