INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.LITIGIOUSINFORMATION
(
	ID,
	ISFCRA,
	ISTCPA,
	ISFDCPA,
	FILEDDATE,	
	UPDATE_DATE,
	CUSTOMERID
)
SELECT 
	SYS_GUID() AS ID,
	a.ARENLITFCRAFLAG AS ISFCRA,
	a.ARENLITTCPAFLAG AS ISTCPA,
	a.ARENLITFDCPAFLAG AS ISFDCPA,
	a.ARENLITFILEDATE + 0.5 AS FILEDDATE,
	SYSDATE AS UPDATE_DATE,
	B.CUSTOMERID
FROM 
	ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_PARTY_INFO a
	INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER b ON a.CONSUMERID=b.MIGRATION_SOURCE_ID  
WHERE a.ARENLITFILEDATE IS NOT NULL