INSERT INTO COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_TRANSACTION
( 
	VERSION,
	CREATE_DATE,
	MODIFIED_ON,	
	CREATE_BY,
	MODIFIED_BY,
	TYPE,
	CHARGE_ITEM_ID,
	TXN_AMT,
	CREDIT,
	EFFECTIVE_DATE,
	REMIT_OVERPYMT_TO_CLIENT,
	PAYMENT_ID,
	POSTED_DATE,
	SETTLEMENT_UNAPPROVED,
	LINE_OF_BUSINESS,
	BUSINESS_CLASS,
	WORKFLOW_STATUS,
	CHARGE_ITEM_BALANCE_DUE,
	ACCOUNT_BALANCE_DUE,
	SHARED_ACCOUNT_BALANCE_DUE,
	CLIENT_ACCOUNT_BALANCE_DUE,
	CLIENT_COMBINED_BALANCE_DUE,
	AGENCY_ACCOUNT_BALANCE_DUE,
	OVERPAYMENT_AMOUNT,
	NET_OFFSET_ADJUSTMENT,
	ACCOUNT_ID,
	FORWARD_COMMISSION_OVERRIDE,
	ATTORNEY_COMMISSION_OVERRIDE,
	LEGAL_PHASE_TYPE_ID,
	REMIT_OVERPYMT_TO_CLIENT_DUP,
	TRANSACTION_UUID,
	ACCOUNT_UUID,
	MIG_SRC_ACCT_ID,
	MIG_SRC_TRAN_ID,
	TRUST_ACCOUNT_ID
)
SELECT 
	0 AS VERSION,
	SYSDATE CREATE_DATE,
	SYSDATE MODIFIED_ON,	
    (
		SELECT IDPUSERID 
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ 
		WHERE USERNAME = 'etlmigrationuser@finvi.com'
	) AS CREATE_BY,	
    (
		SELECT IDPUSERID 
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ 
		WHERE USERNAME = 'etlmigrationuser@finvi.com'
	) AS MODIFIED_BY,			
	130 AS TYPE,
	TCI.CHARGE_ITEM_ID AS CHARGE_ITEM_ID,
	TRN.TRN_AMT  ,
	1 AS CREDIT,
	TRN.AFTREFFDTE AS EFFECTIVE_DATE,
	0 AS REMIT_OVERPYMT_TO_CLIENT,
	TDP.PAYMENT_ID AS PAYMENT_ID,
	TRN.AFTRACCTDTE AS POSTED_DATE,
	0 AS SETTLEMENT_UNAPPROVED,
	'Collections' LINE_OF_BUSINESS,	
	'Commercial' AS BUSINESS_CLASS,
	'New' AS WORKFLOW_STATUS,
	TCI.CHARGE_AMOUNT AS CHARGE_ITEM_BALANCE_DUE,
	A.BALANCE AS ACCOUNT_BALANCE_DUE,				 
	A.BALANCE AS SHARED_ACCOUNT_BALANCE_DUE,
	0 AS CLIENT_ACCOUNT_BALANCE_DUE,
	A.BALANCE AS CLIENT_COMBINED_BALANCE_DUE,
	0 AS AGENCY_ACCOUNT_BALANCE_DUE,
	NVL(TRN.AFSCOVERAMT, 0) AS OVERPAYMENT_AMOUNT,
	0 AS NET_OFFSET_ADJUSTMENT,
	TDA.ACCOUNT_ID AS ACCOUNT_ID,
	0 AS FORWARD_COMMISSION_OVERRIDE,
	0 AS ATTORNEY_COMMISSION_OVERRIDE,
	1 AS LEGAL_PHASE_TYPE_ID,
	'N' AS REMIT_OVERPYMT_TO_CLIENT_DUP,
	LOWER(SUBSTR(TRAN_UUID,1,8) || '-' || SUBSTR(TRAN_UUID,9,4) || '-' || SUBSTR(TRAN_UUID,13,4) || '-' || SUBSTR(TRAN_UUID,17,4) || '-' || SUBSTR(TRAN_UUID,21)) AS TRANSACTION_UUID,
	TDA.ACCOUNT_UUID AS ACCOUNT_UUID,	
	TDP.MIG_SRC_ACCT_ID,
	SOURCETRANSACTIONID AS MIG_SRC_TRAN_ID	, 
	( SELECT UUID FROM COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_CORE_JOURNAL_ACCOUNT tcja WHERE account_type = 'TRUST' AND ROWNUM =1) AS TRUST_ACCOUNT_ID
 FROM 
	( 
		SELECT 
			SOURCETRANSACTIONID ,  
			ACCOUNTID , 
			AFTREFFDTE + 0.5 AS AFTREFFDTE, 	 
			AFTRACCTDTE + 0.5 AS AFTRACCTDTE, 
			DESCRIPTION, 
			AFTRTYP ,  
			TRN_AMT, 
			AFSCOVERAMT, 
			SYS_GUID() AS TRAN_UUID 
		FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_TRAN_HIST STG	 
			UNPIVOT 
			(  
				TRN_AMT
				FOR  DESCRIPTION
				IN ( PRNAPPLYAMT AS 'PRN', INTAPPLYAMT AS 'INT', LI3BALAPPLYAMT AS 'LI3', LI4BALAPPLYAMT AS 'LI4', AININTAPPLYAMT AS 'AIN')	
			)
		WHERE AFTRTYP IN 
		(
			SELECT code 
			FROM COM_FINVI_OASIS_TRANSACTIONCODES_{PP_TenantName}.AJ_CORE_TRANSACTION_CODE TC
			WHERE TC.TRANSACTION_TYPE NOT IN ('Adjustment','Reversal')  
		)  
	) TRN
INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNT A 
	ON A.MIGRATION_SOURCE_ID = TRN.ACCOUNTID
INNER JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_ACCOUNT TDA 
	ON --REPLACE (TDA.ACCOUNT_UUID, '-', '') = LOWER(A.UUID)
	A.MIGRATION_SOURCE_ID= TDA.MIG_SRC_ACCT_ID 
INNER JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_CHARGE_ITEM TCI
	ON TCI.ACCOUNT_ID = TDA.ACCOUNT_ID AND TCI.DESCRIPTION = TRN.DESCRIPTION
INNER JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_PAYMENT TDP 
	ON TDP.MIG_SRC_TRAN_ID = TRN.SOURCETRANSACTIONID AND 
	TDP.MIG_SRC_ACCT_ID = TDA.MIG_SRC_ACCT_ID