INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLEINDEX 
(
	UUID,
	RESPONSIBLEID,
	CREATEDATE, 
	LASTUPDATEDATE,
	CREATED_BY, 
	MODIFIED_BY,
	CUSTOMERINFOID, 
	ISBANKRUPTED,
	ISDISPUTED,
	STATUSCODEID,
	ISSUSPEND,
	SETID	
)
SELECT DISTINCT 
	SYS_GUID() AS UUID,
	R.RESPONSIBLEID,
	sysdate AS CREATEDATE,
	sysdate AS LASTUPDATEDATE,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATED_BY,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIED_BY,	
	C.CUSTOMERID,
	CASE WHEN pi.ARENBNKRPT = 'Y' THEN 1 ELSE 0 END AS ISBANKRUPTED,
	CASE WHEN a.IS_DISPUTED = 'Y' THEN 1 ELSE 0 END AS ISDISPUTED,
	(SELECT UUID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.AJCORESTATUSCODE WHERE CODE = 'NEW') AS STATUSCODEID,
	CASE WHEN a.ISSUSPEND = 'Y' THEN 1 ELSE 0 END AS ISSUSPEND,
	SYS_GUID() AS SETID
FROM 
	ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_PARTY_INFO PI,
	ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_ACCOUNT_INFO A,
	COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLE R,
	COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER C
WHERE 
	PI.ACCOUNTID = R.MIG_SRC_ACCT_ID
	AND PI.ACCOUNTID = A.ACCOUNTID
	AND PI.CONSUMERID = R.MIG_SRC_CONS_ID 
	AND C.MIGRATION_SOURCE_ID = PI.CONSUMERID