INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.BANKRUPTCYTRUSTEEINFORMATION
(
	UUID,
	LASTNAME,
	ADDRESSLINE1,
	ADDRESSLINE2,
	CITY,
	STATEID,
	POSTALCODE,
	PHONE,
	MIGRATION_SOURCE_ID		
)
SELECT 
	SYS_GUID() AS UUID,
	PI.ARENLGLTRSTNAMEBKR,
	PI.ARENLGLTRSTADR1BKR,
	PI.ARENLGLTRSTADR2BKR,
	PI.ARENLGLTRSTCITYBKR,
	S.ID AS STATEID,	
	PI.ARENLGLTRSTZIPBKR,
	PI.ARENLGLTRSTPHONEBKR,
	PI.CONSUMERID AS MIGRATION_SOURCE_ID	
FROM 
	ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_PARTY_INFO  PI
	INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER CN ON PI.CONSUMERID = CN.MIGRATION_SOURCE_ID
	LEFT OUTER JOIN COM_FINVI_OASIS_STATIC_DATA_{PP_TenantName}.STATE S ON PI.ARENLGLTRSTSTBKR = S.CODE
WHERE PI.ARENBNKRPT='Y'