INSERT INTO COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_ADJUSTMENT
(
	ADJ_AMOUNT, 
	CREATE_DATE,
	MODIFIED_ON,
	CREATE_BY,
	MODIFIED_BY,
	VERSION,
	"TYPE", 
	REFERENCE_ID,
	ADJUSTMENT_UUID,
 	CONSUMER_UUID,
 	POSTING_DATE,
 	EFFECTIVE_DATE,
 	ACCOUNT_UUID,
	TRANSACTION_CODE_UUID,
	INITIATION_ACCOUNT_UUID,
	MIG_SRC_TRAN_ID,
	BATCH_UUID,
	MIG_SRC_ACCT_ID,
	TRANSACTION_SOURCE	
)
WITH CTE_ADJUSTMENT AS 
(
SELECT 
	ADJ_AMOUNT, 
	CREATE_DATE,
	MODIFIED_ON,
	CREATE_BY,
	MODIFIED_BY,
	VERSION,
	"TYPE", 
	REFERENCE_ID,
	LOWER( SUBSTR(ADJ_UUID,1,8) || '-' || SUBSTR(ADJ_UUID,9,4) || '-' || SUBSTR(ADJ_UUID,13,4) || '-' || SUBSTR(ADJ_UUID,17,4) || '-' || SUBSTR(ADJ_UUID,21)) AS ADJUSTMENT_UUID,
 	LOWER( SUBSTR(CON_UUID,1,8) || '-' || SUBSTR(CON_UUID,9,4) || '-' || SUBSTR(CON_UUID,13,4) || '-' || SUBSTR(CON_UUID,17,4) || '-' || SUBSTR(CON_UUID,21)) AS CONSUMER_UUID,
 	POSTING_DATE,
 	EFFECTIVE_DATE,
 	ACCOUNT_UUID,
	TRANSACTION_CODE_UUID,
	INITIATION_ACCOUNT_UUID,
	SOURCETRANSACTIONID,
	Batch_no,
	ACCOUNTID,
	'AGENT_PORTAL' AS TRANSACTION_SOURCE 			
FROM 
(
	SELECT 
		NVL(T.PRNAPPLYAMT,0) + NVL( T.LI4BALAPPLYAMT,0) + NVL( T.LI3BALAPPLYAMT,0) + NVL( T.INTAPPLYAMT,0) + NVL( T.AININTAPPLYAMT,0) ADJ_AMOUNT,
		SYSDATE AS CREATE_DATE,
		SYSDATE AS MODIFIED_ON,
		(SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATE_BY,
		(SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIED_BY,		
		0 AS VERSION,
		0 AS "TYPE",
		T.SOURCETRANSACTIONID AS REFERENCE_ID,
		SYS_GUID() AS ADJ_UUID,
	 	C.UUID AS CON_UUID,
	 	T.AFTREFFDTE + 0.5 AS POSTING_DATE,
	 	T.AFTREFFDTE + 0.5 AS EFFECTIVE_DATE,
	 	TDA.ACCOUNT_UUID AS ACCOUNT_UUID,
		LOWER( SUBSTR(TC.UUID,1,8) || '-' || SUBSTR(TC.UUID,9,4) || '-' || SUBSTR(TC.UUID,13,4) || '-' || SUBSTR(TC.UUID,17,4) || '-' || SUBSTR(TC.UUID,21)) AS TRANSACTION_CODE_UUID,
		TDA.ACCOUNT_UUID AS INITIATION_ACCOUNT_UUID,
		T.SOURCETRANSACTIONID AS SOURCETRANSACTIONID,
		TC.code ,
		T.AFTRTYP ,
		T.ACCOUNTID,
		CEIL( ROWNUM / 1000 ) as Batch_no 
	FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_TRAN_HIST T
	INNER JOIN ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_PARTY_INFO P
		ON P.ACCOUNTID  = T.ACCOUNTID 
		AND P.ARRELTYPID = 'Primary'
	INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER C 
		ON C.MIGRATION_SOURCE_ID = P.CONSUMERID 
	INNER JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_ACCOUNT TDA 
		ON T.ACCOUNTID = TDA.MIG_SRC_ACCT_ID
	INNER JOIN COM_FINVI_OASIS_TRANSACTIONCODES_{PP_TenantName}.AJ_CORE_TRANSACTION_CODE TC
		ON TC.TRANSACTION_TYPE='Adjustment' AND TC.code= T.AFTRTYP	 
)
)
SELECT 
CA.ADJ_AMOUNT
,CA.CREATE_DATE
,CA.MODIFIED_ON
,CA.CREATE_BY
,CA.MODIFIED_BY
,CA.VERSION
,CA.TYPE
,CA.REFERENCE_ID
,CA.ADJUSTMENT_UUID
,CA.CONSUMER_UUID
,CA.POSTING_DATE
,CA.EFFECTIVE_DATE
,CA.ACCOUNT_UUID
,CA.TRANSACTION_CODE_UUID
,CA.INITIATION_ACCOUNT_UUID
,CA.SOURCETRANSACTIONID
,BT.UUID AS BATCH_UUID
,CA.ACCOUNTID
,CA.TRANSACTION_SOURCE
FROM CTE_ADJUSTMENT CA 
INNER JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_BATCH BT
	ON TO_CHAR(CA.Batch_no) || '-Adjustment' = BT.COMMENT_
WHERE BT.IS_DELETED <> 1 
AND BT.CREATED_BY = (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com')