INSERT INTO COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_TRANSACTION
(
	VERSION,
	CREATE_DATE,
	MODIFIED_ON,	
	CREATE_BY,
	MODIFIED_BY,
	TYPE,
	CHARGE_ITEM_ID,
	TXN_AMT,
	CREDIT,
	EFFECTIVE_DATE,
	REMIT_OVERPYMT_TO_CLIENT,
	PAYMENT_ID,
	PAYMENT_REVERSAL_ID ,
	REVERSES_TRANSACTION_ID ,
	POSTED_DATE,
	SETTLEMENT_UNAPPROVED,
	LINE_OF_BUSINESS,
	BUSINESS_CLASS,
	WORKFLOW_STATUS,
	CHARGE_ITEM_BALANCE_DUE,
	ACCOUNT_BALANCE_DUE,
	SHARED_ACCOUNT_BALANCE_DUE,
	CLIENT_ACCOUNT_BALANCE_DUE,
	CLIENT_COMBINED_BALANCE_DUE,
	AGENCY_ACCOUNT_BALANCE_DUE,
	OVERPAYMENT_AMOUNT,
	NET_OFFSET_ADJUSTMENT,
	ACCOUNT_ID,
	FORWARD_COMMISSION_OVERRIDE,
	ATTORNEY_COMMISSION_OVERRIDE,
	PAID_TO,
	PAYMENT_TYPE_INT,
	LEGAL_PHASE_TYPE_ID,
	REMIT_OVERPYMT_TO_CLIENT_DUP,
	TRANSACTION_UUID,
	ACCOUNT_UUID ,
	MIG_SRC_ACCT_ID,
	MIG_SRC_TRAN_ID,
	TRUST_ACCOUNT_ID
)
SELECT
	0 AS VERSION,
	SYSDATE CREATE_DATE,
	SYSDATE MODIFIED_ON,	
    (
		SELECT IDPUSERID 
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ 
		WHERE USERNAME = 'etlmigrationuser@finvi.com'
	) AS CREATE_BY,	
    (
		SELECT IDPUSERID 
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ 
		WHERE USERNAME = 'etlmigrationuser@finvi.com'
	) AS MODIFIED_BY,
	130 AS TYPE,
	TCI.CHARGE_ITEM_ID AS CHARGE_ITEM_ID,
	TRN.TRN_AMT AS TXN_AMT,
	1 AS CREDIT,
	TRN.AFTREFFDTE AS EFFECTIVE_DATE,
	0 AS REMIT_OVERPYMT_TO_CLIENT,
	tdpr.PAYMENT_ID AS PAYMENT_ID,
	tdpr.PAYMENT_REVERSAL_ID,
	TDT.TRANSACTION_ID AS REVERSES_TRANSACTION_ID ,
	TRN.AFTRACCTDTE  AS POSTED_DATE,
	0 AS SETTLEMENT_UNAPPROVED,
	'Collections' LINE_OF_BUSINESS,	
	'Commercial' AS BUSINESS_CLASS,
	'New' AS WORKFLOW_STATUS,
	TCI.CHARGE_AMOUNT AS CHARGE_ITEM_BALANCE_DUE,
	A.BALANCE AS ACCOUNT_BALANCE_DUE,					 
	A.BALANCE AS SHARED_ACCOUNT_BALANCE_DUE,
	0 AS CLIENT_ACCOUNT_BALANCE_DUE,
	A.BALANCE AS CLIENT_COMBINED_BALANCE_DUE,
	0 AS AGENCY_ACCOUNT_BALANCE_DUE,
	NVL(TRN.AFSCOVERAMT, 0) AS OVERPAYMENT_AMOUNT,
	0 AS NET_OFFSET_ADJUSTMENT,
	TDA.ACCOUNT_ID AS ACCOUNT_ID,
	0 AS FORWARD_COMMISSION_OVERRIDE,
	0 AS ATTORNEY_COMMISSION_OVERRIDE,
	1 AS PAID_TO,
	101 AS PAYMENT_TYPE_INT,
	1 AS LEGAL_PHASE_TYPE_ID,
	'N' AS REMIT_OVERPYMT_TO_CLIENT_DUP,
	LOWER
	(
		SUBSTR(TRN.UUID,1,8) || '-' ||
		SUBSTR(TRN.UUID,9,4) || '-' ||
		SUBSTR(TRN.UUID,13,4) || '-' ||
		SUBSTR(TRN.UUID,17,4) || '-' ||
		SUBSTR(TRN.UUID,21)
	)   AS TRANSACTION_UUID,
	TDA.ACCOUNT_UUID AS ACCOUNT_UUID,
	tdpr.MIG_SRC_ACCT_ID,
	TRN.SOURCETRANSACTIONID AS MIG_SRC_TRAN_ID,
	( SELECT UUID FROM COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_CORE_JOURNAL_ACCOUNT tcja WHERE account_type = 'TRUST' AND ROWNUM =1) AS TRUST_ACCOUNT_ID
FROM 
(
	SELECT 
		SOURCETRANSACTIONID, 
		ACCOUNTID, 
		AFTREFFDTE + 0.5 AS AFTREFFDTE,
		AFTRACCTDTE + 0.5 AS AFTRACCTDTE,
		DESCRIPTION, 
		TRN_AMT, 
		AFSCOVERAMT, 
		SYS_GUID() AS UUID 
	FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_TRAN_HIST STG
		UNPIVOT 
			( 
				TRN_AMT
				FOR DESCRIPTION
				IN ( PRNAPPLYAMT AS 'PRN', INTAPPLYAMT AS 'INT', LI3BALAPPLYAMT AS 'LI3', LI4BALAPPLYAMT AS 'LI4', AININTAPPLYAMT AS 'AIN')	
			)
	WHERE AFTRTYP IN (SELECT code FROM COM_FINVI_OASIS_TRANSACTIONCODES_{PP_TenantName}.AJ_CORE_TRANSACTION_CODE TC where TC.TRANSACTION_TYPE=  'Reversal')  
) TRN
INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNT A
	ON A.MIGRATION_SOURCE_ID = TRN.ACCOUNTID
INNER JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_ACCOUNT TDA
	ON TDA.MIG_SRC_ACCT_ID = TRN.ACCOUNTID
INNER JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_CHARGE_ITEM TCI
	ON TCI.ACCOUNT_ID = TDA.ACCOUNT_ID AND TCI.DESCRIPTION = TRN.DESCRIPTION
INNER JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_PAYMENT_REVERSAL tdpr 
	ON tdpr.MIG_SRC_TRAN_ID = TRN.SOURCETRANSACTIONID
LEFT JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_TRANSACTION TDT -- DONT remove LEFT JOIN
	ON tdpr.PAYMENT_ID  = TDT.PAYMENT_ID AND TCI.CHARGE_ITEM_ID = TDT.CHARGE_ITEM_ID
		AND TDT.REVERSES_TRANSACTION_ID  IS NULL AND  TDT.TYPE = 130 -- dont remove 