INSERT INTO COM_FINVI_OASIS_ACCOUNT_ACTIVITY_{PP_TenantName}.RELATED_ENTITY
(
	ID, 
	ACTIVITY_ID, 
	RELATED_ENTITY_ID, 
	CREATED_ON, 
	MODIFIED_ON
)
SELECT 
	SYS_GUID() AS ID ,
	a.id  AS ACTIVITY_ID,
	LOWER
	(
		SUBSTR(a1.UUID,1,8) || '-' ||
		SUBSTR(a1.UUID,9,4) || '-' ||
		SUBSTR(a1.UUID,13,4) || '-' ||
		SUBSTR(a1.UUID,17,4) || '-' ||
		SUBSTR(a1.UUID,21)
	) AS RELATED_ENTITY_ID,
	CURRENT_TIMESTAMP AS CREATED_ON,
	CURRENT_TIMESTAMP AS MODIFIED_ON		 
FROM COM_FINVI_OASIS_ACCOUNT_ACTIVITY_{PP_TenantName}.ACTIVITY a 
	JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNT a1 
		ON a1.ACCOUNTNUM = JSON_VALUE( DATA  , '$.transactions[0].accountNum') 
	JOIN ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_TRAN_HIST est 
    	ON est.SOURCETRANSACTIONID = JSON_VALUE( DATA  , '$.migrationSourceId') 
    	AND est.ACCOUNTID= a1.MIGRATION_SOURCE_ID
	LEFT JOIN COM_FINVI_OASIS_ACCOUNT_ACTIVITY_{PP_TenantName}.RELATED_ENTITY re 
 		ON a.ID = re.ACTIVITY_ID 
WHERE re.ACTIVITY_ID IS NULL 
	AND a.CONTEXT = 'ACCOUNT'  
	AND a.CATEGORY = 'PAYMENT' 