INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.NOTES
(
	CONTENT,
	SPECIAL,
	CREATEDAT,
	CREATEDBY,
	UPDATEDAT,
	UPDATEDBY,
	ID,
	TYPE,
	MIG_SRC_ACCT_ID,
	MIG_SRC_CONS_ID
) 
SELECT 
	CASE WHEN (pn.NOTETEXT IS NOT NULL AND pn.NOTEUSER IS NOT NULL) 
		THEN pn.NOTEUSER || ' - ' || pn.NOTETEXT 
		ELSE pn.NOTETEXT 
	END AS CONTENT, 
	'0' AS SPECIAL,
	CASE WHEN CAST(SUBSTR(pn.NOTETIME,1,2) AS INTEGER) > 23 
		THEN TO_DATE((TO_CHAR(COALESCE(pn.NOTEDATE,(TO_DATE('1950-01-01','YYYY-MM-DD'))),'YYYY-MM-DD') || ' 23:59:00'),'YYYY-MM-DD HH24:MI:SS')	
		ELSE TO_DATE((TO_CHAR(COALESCE(pn.NOTEDATE,(TO_DATE('1950-01-01','YYYY-MM-DD'))),'YYYY-MM-DD') || ' ' || pn.NOTETIME || ':00'),'YYYY-MM-DD HH24:MI:SS')	
	END AS CREATEDAT, 
    (
		SELECT IDPUSERID 
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ 
		WHERE USERNAME = 'etlmigrationuser@finvi.com'
	) AS CREATEDBY,	 	
	CASE WHEN CAST(SUBSTR(pn.NOTETIME,1,2) AS INTEGER) > 23 
		THEN TO_DATE((TO_CHAR(COALESCE(pn.NOTEDATE,(TO_DATE('1950-01-01','YYYY-MM-DD'))),'YYYY-MM-DD') || ' 23:59:00'),'YYYY-MM-DD HH24:MI:SS')	
		ELSE TO_DATE((TO_CHAR(COALESCE(pn.NOTEDATE,(TO_DATE('1950-01-01','YYYY-MM-DD'))),'YYYY-MM-DD') || ' ' || pn.NOTETIME || ':00'),'YYYY-MM-DD HH24:MI:SS')	
	END AS UPDATEDAT, 
    (
		SELECT IDPUSERID 
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ 
		WHERE USERNAME = 'etlmigrationuser@finvi.com'
	) AS UPDATEDBY,	
	SYS_GUID() AS ID,
	pn.NOTETYPE AS TYPE,
	pn.ACCOUNTID AS MIG_SRC_ACCT_ID,
	pn.CONSUMERID AS MIG_SRC_CONS_ID	
FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_PRTY_NOTES pn