INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.EXECUTOR
(
	UUID,
	LASTNAME,
	CITY,
	STATEREFID,
	ZIPCODE,
	PHONENUMBER,
	MIGRATION_SOURCE_ID
)
SELECT 
	SYS_GUID() AS UUID,
	a.ARENLGLEXECNAMEDS AS LASTNAME, 
	a.ARENLGLEXECCITYDS AS CITY,
	S.ID AS STATEREFID,
	a.ARENLGLEXECZIPDS AS ZIPCODE,
	a.ARENLGLEXECPHONEDS AS PHONENUMBER,
	a.CONSUMERID AS MIGRATION_SOURCE_ID
FROM 
	ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_PARTY_INFO a
	INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER b ON a.CONSUMERID = b.MIGRATION_SOURCE_ID  
	LEFT OUTER JOIN COM_FINVI_OASIS_STATIC_DATA_{PP_TenantName}.STATE S ON S.CODE = a.ARENLGLEXECSTDS
WHERE a.ARENDECEASED = 'Y'