INSERT INTO	COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_PAYMENT_REVERSAL
(  
	PAYMENT_ID,  
	CREATE_DATE,
	MODIFIED_ON,
	CREATE_BY,
	MODIFIED_BY,	
	VERSION,
	EFFECTIVE_DATE,
	TYPE,
	REVERSAL_AMOUNT,
	POSTED_DATE,
	CONSUMER_UUID,
	MIG_SRC_TRAN_ID,
	PAYMENT_REVERSAL_UUID,
	BATCH_UUID,
	TRANSACTION_CODE_UUID,
	INITIATION_ACCOUNT_UUID,
	MIG_SRC_ACCT_ID,
	TRANSACTION_SOURCE	
) 
WITH CTE2 AS 
(
SELECT 
	DISTINCT
    tdp.PAyment_id , 
	SYSDATE AS CREATE_DATE,
	SYSDATE AS MODIFIED_ON,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATE_BY,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIED_BY,	
	0 AS version,
	th.AFTREFFDTE + 0.5 AS EFFECTIVE_DATE, 
	100 AS TYPE,  
	NVL(th.PRNAPPLYAMT,0) + NVL( th.LI4BALAPPLYAMT,0) + NVL( th.LI3BALAPPLYAMT,0) + NVL( th.INTAPPLYAMT,0) + NVL( th.AININTAPPLYAMT,0) AS REVERSAL_AMOUNT,
	th.AFTREFFDTE + 0.5 AS POSTED_DATE , 
 	tdp.CONSUMER_UUID AS CONSUMER_UUID,
	th.SOURCETRANSACTIONID  AS MIGRATION_SOURCE_ID,
	LOWER
	(
		SUBSTR(th.UUID,1,8) || '-' ||
		SUBSTR(th.UUID,9,4) || '-' ||
		SUBSTR(th.UUID,13,4) || '-' ||
		SUBSTR(th.UUID,17,4) || '-' ||
		SUBSTR(th.UUID,21)
	) AS PAYMENT_REVERSAL_UUID,
	LOWER
	(
		SUBSTR(ajcr.UUID,1,8) || '-' ||
		SUBSTR(ajcr.UUID,9,4) || '-' ||
		SUBSTR(ajcr.UUID,13,4) || '-' ||
		SUBSTR(ajcr.UUID,17,4) || '-' ||
		SUBSTR(ajcr.UUID,21)
	) AS TRANSACTION_CODE_UUID,
	tdp.PAYMENT_INITIATION_ACCOUNT AS  INITIATION_ACCOUNT_UUID,
	th.ACCOUNTID,
	'AGENT_PORTAL' AS TRANSACTION_SOURCE 	,
	CEIL( ROWNUM / 1000 ) as BATCH_NO
FROM
	COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_PAYMENT tdp   
	JOIN (SELECT a.* , SYS_GUID() AS UUID FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_TRAN_HIST a)   th  
		ON th.ACCOUNTID = tdp.MIG_SRC_ACCT_ID AND th.POINTERTOREVERSED =  tdp.MIG_SRC_TRAN_ID 
	JOIN COM_FINVI_OASIS_TRANSACTIONCODES_{PP_TenantName}.AJ_CORE_TRANSACTION_CODE ajcr 
		ON  ajcr.CODE = th.AFTRTYP AND ajcr.TRANSACTION_TYPE IN ( 'Reversal') 
		
)
SELECT 	
CTE2.PAYMENT_ID
,CTE2.CREATE_DATE
,CTE2.MODIFIED_ON
,CTE2.CREATE_BY
,CTE2.MODIFIED_BY
,CTE2.VERSION
,CTE2.EFFECTIVE_DATE
,CTE2.TYPE
,CTE2.REVERSAL_AMOUNT
,CTE2.POSTED_DATE
,CTE2.CONSUMER_UUID
,CTE2.MIGRATION_SOURCE_ID AS MIG_SRC_TRAN_ID
,CTE2.PAYMENT_REVERSAL_UUID
,BT.UUID AS BATCH_UUID
,CTE2.TRANSACTION_CODE_UUID 
,CTE2.INITIATION_ACCOUNT_UUID
,CTE2.ACCOUNTID AS MIG_SRC_ACCT_ID
,CTE2.TRANSACTION_SOURCE 
FROM CTE2
LEFT JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_BATCH BT
	ON TO_CHAR(CTE2.BATCH_NO) || '-Reversal' = BT.COMMENT_
WHERE BT.IS_DELETED <> 1
AND BT.CREATED_BY = (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com')