INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.STATUTE_INFORMATION
(
	UUID,
	BASE_DATE,
	BASE_DATE_DESCRIPTION,
	BASE_DATE_TYPE,
	EXPIRATION_DATE,
	ACCOUNT_NUM,
	VENUE,
	DAYS_BEFORE_STATUTE_EXPIRES,
	CREATED_ON,
	MODIFIED_ON,
	CREATED_BY,
	MODIFIED_BY
) 
SELECT 
	SYS_GUID() AS UUID, 
	CASE 
		WHEN COALESCE(EI.ARACSTATUTEBASEDTE,TO_DATE('1900-01-01','YYYY/MM/DD')) > 
			COALESCE(EI.ARACCNVLPYDTE,TO_DATE('1900-01-01','YYYY/MM/DD')) 
		THEN EI.ARACSTATUTEBASEDTE + 0.5 
		ELSE EI.ARACCNVLPYDTE + 0.5 
	END AS BASE_DATE,
	CASE 
		WHEN COALESCE(EI.ARACSTATUTEBASEDTE,TO_DATE('1900-01-01','YYYY/MM/DD')) >
			COALESCE(EI.ARACCNVLPYDTE,TO_DATE('1900-01-01','YYYY/MM/DD')) 
		THEN 'Delinquency Date' 
		ELSE 'Account Last Payment Date' 
	END AS BASE_DATE_DESCRIPTION,
	CASE 
		WHEN COALESCE(EI.ARACSTATUTEBASEDTE,TO_DATE('1900-01-01','YYYY/MM/DD')) >
			COALESCE(EI.ARACCNVLPYDTE,TO_DATE('1900-01-01','YYYY/MM/DD')) 
		THEN '2' 
		ELSE '1' 
	END AS BASE_DATE_TYPE,
	CASE 
		WHEN COALESCE(EI.ARACSTATUTEBASEDTE,TO_DATE('1900-01-01','YYYY/MM/DD')) > 
			COALESCE(EI.ARACCNVLPYDTE,TO_DATE('1900-01-01','YYYY/MM/DD')) 
		THEN EI.ARACSTATUTEBASEDTE + COALESCE(ajco.DAYS_UNTIL_OUT_OF_STATUTE,2190)
		ELSE EI.ARACCNVLPYDTE + COALESCE(ajco.DAYS_UNTIL_OUT_OF_STATUTE,2190)
	END AS EXPIRATION_DATE,
	A.ACCOUNTNUM,
	hextoraw(replace(( SELECT ID FROM COM_FINVI_OASIS_STATIC_DATA_{PP_TenantName}.STATE WHERE code = ei.ARACSTATUTESTATEID ) ,'-','')) AS VENUE,
	ajco.DAYS_UNTIL_OUT_OF_STATUTE AS DAYS_BEFORE_STATUTE_EXPIRES,
	SYSDATE AS CREATED_ON,
	SYSDATE AS MODIFIED_ON,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATED_BY,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIED_BY
FROM
	ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_ACCOUNT_INFO EI
	INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNT a ON a.MIGRATION_SOURCE_ID = EI.ACCOUNTID
	LEFT OUTER JOIN COM_FINVI_OASIS_CLIENTANDCREDITOR_{PP_TenantName}.AJ_CORE_ORGANIZATION ajco ON ajco.UUID = a.CLIENTCONTRACTID
WHERE (EI.ARACSTATUTEBASEFLD IS NOT NULL OR EI.ARACSTATUTEBASEDTE IS NOT NULL OR EI.ARACSTATUTEEXPDTE IS NOT NULL)