INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.LETTERCHANNELRESULT
(
	CREATEDATE,
	STATUS,
	STRATEGYDATE,
	LASTUPDATEDATE,
	BALANCE,
	DOCUMENTID,
	TEMPLATE,
	DELTABATCH,
	ACCOUNTNUM,
	RESPONSIBLEID,
	TRANSACTION_ID,
	UUID,
	INTEGRATEDID,
	CHANNELACTIONID,
	CREATED_BY,
	MODIFIED_BY,
	BCNODEID
)
SELECT
	SYSDATE  AS CREATEDATE,
	'SENT' AS STATUS, 
	slh.ARLHPRTDTE AS STRATEGYDATE,
	SYSDATE AS LASTUPDATEDATE,
	a.BALANCE AS BALANCE,
	( SELECT DISTINCT e.ID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CHANNELACTION ca
		INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ENTERPRISEDOCUMENT e ON e.ID=ca.ENTERPRISEDOCUMENTID 
		WHERE ca.TEMPLATETYPE='letter' AND e.NAME=slh.ARLHLTR ) AS DOCUMENTID,
	( SELECT DISTINCT e.name FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CHANNELACTION ca
		INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ENTERPRISEDOCUMENT e ON e.ID=ca.ENTERPRISEDOCUMENTID 
		WHERE ca.TEMPLATETYPE='letter' AND e.NAME=slh.ARLHLTR ) as TEMPLATE,
	'N' AS DELTABATCH,
	a.ACCOUNTNUM AS ACCOUNTNUM,
	rir.RESPONSIBLEID,
	SYS_GUID() AS TRANSACTION_ID,
	SYS_GUID() AS UUID, 
	( SELECT oip.UUID FROM COM_FINVI_OASIS_STATIC_DATA_{PP_TenantName}.OAS_INTEGRATED_PARTNER oip 
		INNER JOIN COM_FINVI_OASIS_STATIC_DATA_{PP_TenantName}.OAS_INTEGRATED_PARTNER_PRODUCT oipp ON oipp.IPARTNER_ID = oip.UUID  
		WHERE oip.PARTNER = 'RevSpring'  AND oipp.CODE = 'NCOA, Letter Print' ) AS INTEGRATEDID, 
	( SELECT DISTINCT ca.id FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CHANNELACTION ca
		INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ENTERPRISEDOCUMENT e ON e.ID=ca.ENTERPRISEDOCUMENTID 
		WHERE ca.TEMPLATETYPE='letter' AND e.NAME=slh.ARLHLTR
		FETCH FIRST 1 ROWS ONLY ) AS CHANNELACTIONID,
    ( SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com' ) AS CREATED_BY,
    ( SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com' ) AS MODIFIED_BY,
    slh.SEQ_NUM AS BCNODEID
FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_PRTY_LTR_HIST_INFO slh
INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNT a ON a.MIGRATION_SOURCE_ID=slh.ACCOUNTID
LEFT JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLE rir ON rir.ACCOUNTNUM = a.ACCOUNTNUM 