INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.NOTES
(
	CONTENT,
	SPECIAL,
	CREATEDAT,
	CREATEDBY,
	UPDATEDAT,
	UPDATEDBY,
	ID,
	TYPE,
	MIG_SRC_ACCT_ID
) 
SELECT 
	CASE WHEN (an.NOTETEXT IS NOT NULL AND an.NOTEUSER IS NOT NULL) 
		THEN an.NOTEUSER || ' - ' || an.NOTETEXT 
		ELSE an.NOTETEXT 
	END AS CONTENT, 
	'0' AS SPECIAL,
	CASE WHEN CAST(SUBSTR(an.NOTETIME,1,2) AS INTEGER) > 23 
		THEN TO_DATE((TO_CHAR(COALESCE(an.NOTEDATE,(TO_DATE('1950-01-01','YYYY-MM-DD'))),'YYYY-MM-DD') || ' 23:59:00'),'YYYY-MM-DD HH24:MI:SS')	
		ELSE TO_DATE((TO_CHAR(COALESCE(an.NOTEDATE,(TO_DATE('1950-01-01','YYYY-MM-DD'))),'YYYY-MM-DD') || ' ' || an.NOTETIME || ':' ||  ROW_NUMBER () OVER (PARTITION BY an.ACCOUNTID, an.NOTEDATE, an.NOTETIME ORDER BY an.ACCOUNTID)),'YYYY-MM-DD HH24:MI:SS')	
	END AS CREATEDAT, 
    (
		SELECT IDPUSERID 
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ 
		WHERE USERNAME = 'etlmigrationuser@finvi.com'
	) AS CREATEDBY,	 		
	CASE WHEN CAST(SUBSTR(an.NOTETIME,1,2) AS INTEGER) > 23 
		THEN TO_DATE((TO_CHAR(COALESCE(an.NOTEDATE,(TO_DATE('1950-01-01','YYYY-MM-DD'))),'YYYY-MM-DD') || ' 23:59:00'),'YYYY-MM-DD HH24:MI:SS')	
		ELSE TO_DATE((TO_CHAR(COALESCE(an.NOTEDATE,(TO_DATE('1950-01-01','YYYY-MM-DD'))),'YYYY-MM-DD') || ' ' || an.NOTETIME || ':' ||  ROW_NUMBER () OVER (PARTITION BY an.ACCOUNTID, an.NOTEDATE, an.NOTETIME ORDER BY an.ACCOUNTID)),'YYYY-MM-DD HH24:MI:SS')	
	END AS UPDATEDAT, 
    (
		SELECT IDPUSERID 
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ 
		WHERE USERNAME = 'etlmigrationuser@finvi.com'
	) AS UPDATEDBY,	
	SYS_GUID() AS ID,
	an.NOTETYPE AS TYPE,
	an.ACCOUNTID AS MIG_SRC_ACCT_ID
FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_ACCT_NOTES an