INSERT INTO COM_FINVI_OASIS_ACCOUNT_ACTIVITY_{PP_TenantName}.ACTIVITY
(
	ID, 
	TRANSACTION_ID, 
	USER_ID,
	CONTEXT, 
	CATEGORY, 
	"TYPE", 
	"DATA",
	DATA_VERSION, 
	"TIMESTAMP", 
	CREATED_ON, 
	MODIFIED_ON
)
SELECT 
	SYS_GUID()  AS ID,
    SYS_GUID()  AS TRANSACTION_ID,
    (
		SELECT IDPUSERID 
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ 
		WHERE USERNAME = 'etlmigrationuser@finvi.com'
	) AS USER_ID,
    'ACCOUNT' AS CONTEXT,
    'PAYMENT' AS CATEGORY,
    'SINGLE_PAYMENT' AS TYPE  ,
    DATA,
    0 AS DATA_VERSION,
    CURRENT_TIMESTAMP AS TIMESTAMP,
    CURRENT_TIMESTAMP AS CREATED_ON,
    CURRENT_TIMESTAMP  AS MODIFIED_ON
FROM 
	(
		SELECT 
			TDP.PAYMENT_ID,
			JSON_OBJECT
			(
				'paymentDate' VALUE tdp.POSTED_DATE
				,'effectiveDate' VALUE tdp.EFFECTIVE_DATE
				,'paymentAmount' VALUE tdp.PAYMENT_AMOUNT       
				,'paymentMethod' VALUE NULL
				,'directed' VALUE 'TRUE'
				,'referenceId' VALUE NULL
				,'status' VALUE 'COMPLETED'
				,'customerId' VALUE tdp.CONSUMER_UUID
				,'responsiblePartyName' VALUE C.CUSTOMERNAME
				,'suffix' VALUE C.SUFFIX
				,'transactions' VALUE JSON_ARRAYAGG(TRN.TRAN_JSON)
				,'sourceSystem' VALUE 'Data Migration'
				,'migrationSourceId' VALUE tdp.MIG_SRC_TRAN_ID
            ) AS DATA     
		FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_TRAN_HIST est
		INNER JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_TRANSACTION tdt
			ON tdt.MIG_SRC_TRAN_ID = est.SOURCETRANSACTIONID 
			AND tdt.MIG_SRC_ACCT_ID = est.ACCOUNTID 
		INNER JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_PAYMENT tdp  
			ON TDT.PAYMENT_ID  = tdp.PAYMENT_ID           	
		INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER c 
			ON RAWTOHEX(c.UUID ) = UPPER(REPLACE (tdp.CONSUMER_UUID , '-', ''))
		INNER JOIN 
		(
			SELECT 
				tdt.PAYMENT_ID,
				JSON_OBJECT
				(
					'accountNum' VALUE a.ACCOUNTNUM, 
					'paymentAmount' VALUE tdp.PAYMENT_AMOUNT,
					'clientName' VALUE c.CUSTOMERNAME,
					'subBalance' VALUE JSON_ARRAYAGG
					(
						JSON_OBJECT
							( 
								'subBalanceCode' VALUE tdci.DESCRIPTION,
								'description' VALUE NULL ,
								'amount' VALUE TXN_AMT ,
								'contingencyFee' VALUE 0)
							)
                ) AS TRAN_JSON
			FROM COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_TRANSACTION tdt
				INNER JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_PAYMENT tdp  
					ON tdt.PAYMENT_ID = tdp.PAYMENT_ID
				LEFT JOIN  COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_CHARGE_ITEM tdci
					ON tdci.CHARGE_ITEM_ID = tdt.CHARGE_ITEM_ID
				INNER JOIN  COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNT a
					ON TDT.MIG_SRC_ACCT_ID = a.MIGRATION_SOURCE_ID 
				INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER c  
					ON RAWTOHEX(c.UUID ) = UPPER(REPLACE (tdp.CONSUMER_UUID , '-', ''))
			WHERE tdt.PAYMENT_ID IS NOT NULL 
				AND tdt.REVERSES_TRANSACTION_ID IS NULL
			GROUP BY tdt.PAYMENT_ID, a.ACCOUNTNUM, tdp.PAYMENT_AMOUNT, c.CUSTOMERNAME
		) TRN ON trn.PAYMENT_ID = tdp.PAYMENT_ID
		GROUP BY 
			TDP.PAYMENT_ID
			, TDP.POSTED_DATE
			, TDP.EFFECTIVE_DATE
			, TDP.PAYMENT_AMOUNT
			, TDP.MIG_SRC_TRAN_ID
			, tdp.CONSUMER_UUID 			
			, C.CUSTOMERNAME
			, C.SUFFIX
	)