INSERT INTO COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_BATCH
(
	VERSION,
	TYPE, 
	CREATE_DATE,
	MODIFIED_ON,
	CREATE_BY,
	IMMEDIATE_POST,
	BATCH_STATUS,
	COMMENT_,
	IS_DELETED,
	CREATED_AT,
	CREATED_BY,
	MODIFIED_BY,
	UPDATE_BY_HISTORY,
	UUID
)
SELECT 
	0 AS VERSION,
	1001 AS TYPE,
	sysdate AS CREATE_DATE,
	sysdate AS MODIFIED_ON,
    (
		SELECT IDPUSERID 
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ 
		WHERE USERNAME = 'etlmigrationuser@finvi.com'
	) AS CREATE_BY,	
	1 AS IMMEDIATE_POST,
	9 AS BATCH_STATUS,
	COMMENT_,
	0 AS IS_DELETED,
	sysdate AS CREATED_AT,
    (
		SELECT IDPUSERID 
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ 
		WHERE USERNAME = 'etlmigrationuser@finvi.com'
	) AS CREATED_BY,
	(
		SELECT IDPUSERID 
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ 
		WHERE USERNAME = 'etlmigrationuser@finvi.com'
	) AS MODIFIED_BY,
    (
		SELECT '{"' || IDPUSERID || '":"etlmigrationuser@finvi.com"}'
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ 
		WHERE USERNAME = 'etlmigrationuser@finvi.com'
	) AS UPDATE_BY_HISTORY,	
	LOWER
	(
		SUBSTR(guid,1,8) || '-' ||
		SUBSTR(guid,9,4) || '-' ||
		SUBSTR(guid,13,4) || '-' ||
		SUBSTR(guid,17,4) || '-' ||
		SUBSTR(guid,21)
	) AS uuid	
FROM 
(
	SELECT SYS_GUID() AS GUID, TO_CHAR(Records) || '-' || TRANSACTION_TYPE AS COMMENT_
	FROM (
		SELECT DISTINCT TRANSACTION_TYPE, CEIL(ROW_NUMBER () OVER ( PARTITION BY TRANSACTION_TYPE ORDER BY CODE)/1000) Records
		FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_TRAN_HIST Th
		INNER JOIN (
			SELECT CODE,  CASE TRANSACTION_TYPE WHEN 'Adjustment' THEN 'Adjustment' WHEN 'Reversal' THEN 'Reversal' ELSE 'Payment' END AS TRANSACTION_TYPE
			FROM COM_FINVI_OASIS_TRANSACTIONCODES_{PP_TenantName}.AJ_CORE_TRANSACTION_CODE
		) ajcr ON ajcr.CODE = th.AFTRTYP
	)
) A
WHERE NOT EXISTS (SELECT 1 FROM T_DATA_BATCH B WHERE B.COMMENT_ = A.COMMENT_)