INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLEALERTS
(
	RESPONSIBLEID,
	DELETED,
	CREATEDAT,
	UPDATEDAT,
	CREATEDBY,
	UPDATEDBY,
	ALERTID,
	ID
)
SELECT 
	RESPONSIBLEID,
	0 AS DELETED,
	sysdate AS CREATEDAT,
	sysdate AS UPDATEDAT,	
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATEDBY,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS UPDATEDBY,	
	SYS_GUID() AS ALERTID,
	SYS_GUID() AS ID
FROM RESPONSIBLE