INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ITEMIZATION_INFORMATION 
(
	UUID  ,
	ITEMIZATION_DATE_AMOUNT  ,
	ITEMIZED_INTEREST  ,
	ITEMIZED_FEES ,  
	ITEMIZED_PAID_AMOUNT ,  
	ITEMIZED_TOTAL_AMOUNT ,  
	ACCOUNT_NUM , 
	CREATED_ON , 
	MODIFIED_ON , 
	CREATED_BY , 
	MODIFIED_BY , 
	ITEMIZATION_DATE_TYPE 
)	
SELECT 
	SYS_GUID()
	,ITEMIZATION_DATE_AMOUNT
	,ITEMIZED_INTEREST
	,ITEMIZED_FEES
	,ITEMIZED_PAID_OR_CREDITED
	,TOTAL_AMOUNT  
	,A.ACCOUNTNUM  
	,SYSDATE   AS CREATED_ON
	,SYSDATE  AS MODIFIED_ON
    ,(SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATED_BY
    ,(SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIED_BY
	,IDT.ID 
FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_ITEMIZATION_INFORMATION  II
	JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNT A ON II.ACCOUNT_ID= A.MIGRATION_SOURCE_ID
	LEFT JOIN COM_FINVI_OASIS_STATIC_DATA_{PP_TenantName}.ITEMIZATION_DATE_TYPE IDT ON UPPER(II.ITEMIZATION_DATE_CATEGORY) = UPPER(NVL(IDT.NAME,'Charge-Off Date'))