INSERT INTO COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_PAYMENT_METHOD 
(
	TYPE, 
	PAYMENT_TYPE_SCODE,
	VERSION,
	DEPOSIT_AMT,
	CREATE_DATE,
	CREATE_BY,
	CURRENCY_ID,
	PPD_AUTHORIZED
)
VALUES
(
	101,
	502,
	0,
	1,
	sysdate,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com'),
	174,
	0
)