INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.NOTES_RESPONSIBLES 
(
	NOTE_ID,
	RESPONSIBLE_ID
)
SELECT 
	n.ID,
	r.RESPONSIBLEID
FROM 
	(
		SELECT DISTINCT a.ACCOUNTID, a.CONSUMERID
		FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_PRTY_NOTES a
	) etln,
	COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.NOTES n, 
	COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLE r
WHERE 
	n.MIG_SRC_CONS_ID IS NOT NULL  
	AND etln.ACCOUNTID = n.MIG_SRC_ACCT_ID 
	AND etln.CONSUMERID = n.MIG_SRC_CONS_ID 
	AND n.MIG_SRC_ACCT_ID = r.MIG_SRC_ACCT_ID
	AND n.MIG_SRC_CONS_ID = r.MIG_SRC_CONS_ID