INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMEREMPLOYMENT 
(	
	UUID,
	CREATEDATE,
	LASTUPDATEDATE,
	CUSTOMERID,
	EMPLOYERNAME,
	ADDRESS,
	ADDRESS2,
	CITY,
	STATEID,
	COUNTRYID,
	ZIPCODE,
	ACTIVE,
	STARTDATE,
	ENDDATE,
	PHONENUMBERONE,
	PHONENUMBERTWO,
	EMPLOYERCONTACT,
	VERIFIED
)
SELECT 
	SYS_GUID() AS UUID, 
	SYSDATE AS CREATEDATE,
	SYSDATE AS LASTUPDATEDATE,
	CN.CUSTOMERID,
	POE.ARPOENAME,
	ARPOEADR1,
	ARPOEADR2,
	ARPOECITY,
	S.ID,
	S.COUNTRY_ID,
	ARPOEZIP,  
	'Y' AS ARPOEACTIVE,
	ARPOEHIREDATE + 0.5,
	ARPOETERMDATE + 0.5,
	ARPHPHONE1,
	ARPHPHONE2,
	TRIM(ARPOECONTACTFNM || ' ' || ARPOECONTACTLNM) AS EMPLOYERCONTACT,	
	'Y' AS VERIFIED
FROM 
	ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_PRTY_POE_INFO POE 
	JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER CN ON CN.MIGRATION_SOURCE_ID =POE.CONSUMERID
	LEFT JOIN COM_FINVI_OASIS_STATIC_DATA_{PP_TenantName}.STATE S ON S.CODE=POE.ARPOEST
WHERE (POE.ARPOENAME IS NOT NULL OR POE.ARPHPHONE1 IS NOT NULL OR POE.ARPHPHONE2 IS NOT NULL)