INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLE
(
	UUID,
	DATEOFBIRTH,
	FIRSTNAME,
	GENDER,
	LASTNAME,
	USERLOGON,
	ACCOUNTNUM,
	CREATEDATE,
	LASTUPDATEDATE,
	CREATED_BY,
	MODIFIED_BY,
	SURVEYROUND, 
	RELATIONSHIPTYPEID,
	MIG_SRC_CONS_ID,
	MIG_SRC_ACCT_ID
)
SELECT 
	SYS_GUID() AS UUID,
	A.ARENBTHDTE,
	A.ARENFNM,
	A.ARENGENDER,
	A.ARENLNM,
	A.CONSUMERID AS USERLOGON,
	AA.ACCOUNTNUM,
	SYSDATE AS CREATEDATE,
	SYSDATE AS LASTUPDATEDATE,	
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATED_BY,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIED_BY,	
	1 SURVEYROUND,
	RT.ID AS RELATIONSHIPTYPEID,
	A.CONSUMERID AS MIG_SRC_CONS_ID,
	A.ACCOUNTID AS MIG_SRC_ACCT_ID
FROM 
	ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_PARTY_INFO A,
	COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNT AA,
	COM_FINVI_OASIS_STATIC_DATA_{PP_TenantName}.RELATIONSHIP_TYPE RT 
WHERE AA.MIGRATION_SOURCE_ID = A.ACCOUNTID
AND RT.NAME = A.ARRELTYPID