INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNTINDEX
(
	ACCOUNTNUM,
	CANCELCODEID,
	CANCELLEDON,
	CREATEDATE, 
	LASTUPDATEDATE,
	CREATED_BY,
	MODIFIED_BY,
	ISCANCELLED,
	LAST4ORIGINALACCOUNTNUMBER,
	SERVICEDATE,
	STATUSCODEID,
	STATUTEINFORMATIONID,
	UUID,
	RUNOPERATIONALSTRATEGIES,
	ITEMIZATIONDATE
)
SELECT 
	A.ACCOUNTNUM,
	ai.ARACCANCID AS CANCELCODEID,	
	ai.ARACCANCDTE + 0.5 AS CANCELLEDON,
	sysdate AS CREATEDATE,
	sysdate AS LASTUPDATEDATE,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATED_BY,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIED_BY,	
	CASE WHEN ai.ARACCANCDTE < sysdate THEN 1 ELSE 0 END AS ISCANCELLED,
	substr(a.ORIGINALACCOUNTNUMBER,-4) AS Last4ORIGINALACCOUNTNUMBER,
	ai.ARACSRVDTE + 0.5 AS SERVICEDATE,
	(SELECT UUID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.AJCORESTATUSCODE WHERE code = 'NEW') AS STATUSCODEID,
	SI.UUID AS STATUTEINFORMATIONID,
	SYS_GUID() AS UUID,
	'Y' AS RUNOPERATIONALSTRATEGIES,
	ei.ITEMIZATION_DATE + 0.5 AS ITEMIZATIONDATE
FROM
	ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_ACCOUNT_INFO ai
	INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNT a ON a.MIGRATION_SOURCE_ID = ai.ACCOUNTID
	LEFT OUTER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.STATUTE_INFORMATION SI ON a.ACCOUNTNUM = SI.ACCOUNT_NUM
	LEFT OUTER JOIN ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_ITEMIZATION_INFORMATION ei ON ai.ACCOUNTID = ei.ACCOUNT_ID 