INSERT INTO COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_ACCOUNT
(
	CREATE_DATE,
	MODIFIED_ON,
	CREATE_BY,
	MODIFIED_BY,
	BUSINESS_CLASS_ID,
	SUSPEND_INTEREST_ACCRUAL,
	COMMISSION_BASIS_INT,
	FORWARDED,
	COMPLIANCE_TRACKING_ACTIVE, /*need to update value for payment to work*/
	REHAB_INELIGIBLE, /*need to update value for payment to work*/
	VERSION,
	CLIENT_CONTRACT_ID,  /* Though Column is non mandatory field this should have value to visible in front end */
   	PLACEMENT_DATE,    /* Column is mandatory field if source is blank pouplate sysdate */
	ACCOUNT_UUID,
	INTEREST_BASE_UUID,
	ACCOUNT_STATUS_UUID,
	COMMISSION_STRATEGY_UUID, /*need to update this from right table*/
	MIG_SRC_ACCT_ID,
	IS_SUIT_FILED,  /*need to update value for payment to work*/
	IS_ON_JUDGMENT,  /*need to update value for payment to work*/
	IS_LEGAL_CASE_ACTIVE,  /*need to update value for payment to work*/
	INCLUDED_ON_BANKRUPTCY,  /*need to update value for payment to work*/
	WKFLOW_SCODE_ID, /*need to update value for payment to work */
	INTEREST_CURRENT_THRU, /*need to update value for payment to work */
	INTEREST_RATE,
	ASSESS_INTEREST
)
SELECT 
	SYSDATE AS CREATE_DATE,
	SYSDATE AS MODIFIED_ON,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATE_BY,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIED_BY,	
	1 AS BUSINESS_CLASS_ID,
	0 AS SUSPEND_INTEREST_ACCRUAL, /* changed from 1 to 0 for the payment to work */
 	2 AS COMMISSION_BASIS_INT, /* changed from 1 to 2 for the payment to work */
	0 AS FORWARDED,
	0 AS COMPLIANCE_TRACKING_ACTIVE,
	0 AS REHAB_INELIGIBLE,
	0 AS VERSION, 
	CASE 
		WHEN acc.CLIENTCONTRACTID IS NULL THEN NULL 
		ELSE
			LOWER(
			SUBSTR(acc.CLIENTCONTRACTID,1,8) || '-' ||
			SUBSTR(acc.CLIENTCONTRACTID,9,4) || '-' ||
			SUBSTR(acc.CLIENTCONTRACTID,13,4) || '-' ||
			SUBSTR(acc.CLIENTCONTRACTID,17,4) || '-' ||
			SUBSTR(acc.CLIENTCONTRACTID,21)) 
	END AS CLIENT_CONTRACT_ID, /* Reference from COM_FINVI_OASIS_{PP_TenantName}.ACCOUNT.CLIENTCONTRACTID */
	CASE WHEN ARACLSTDTE IS NOT NULL THEN ARACLSTDTE + 0.5
		ELSE SYSDATE
	END AS PLACEMENT_DATE,	/* WHEN SOURCE IS BLANK THEN UPDATE SYSDATE */	
	CASE WHEN acc.UUID IS NOT NULL THEN 
		LOWER(
			SUBSTR(acc.UUID,1,8) || '-' ||
			SUBSTR(acc.UUID,9,4) || '-' ||
			SUBSTR(acc.UUID,13,4) || '-' ||
			SUBSTR(acc.UUID,17,4) || '-' ||
			SUBSTR(acc.UUID,21))
	END AS ACCOUNT_UUID,
	(
		SELECT 
			CASE WHEN UUID IS NOT NULL THEN 
				LOWER(
				SUBSTR(UUID,1,8) || '-' ||
				SUBSTR(UUID,9,4) || '-' ||
				SUBSTR(UUID,13,4) || '-' ||
				SUBSTR(UUID,17,4) || '-' ||
				SUBSTR(UUID,21)) 
			END AS UUID 
		FROM COM_FINVI_OASIS_INTERESTBASE_{PP_TenantName}.AJ_CORE_INTEREST_BASE /* Remove update statement */
		WHERE CODE = 'GEN'
	) AS INTEREST_BASE_UUID,           /* Removed update statement */
	(
		SELECT 
			CASE WHEN UUID IS NOT NULL THEN 
				LOWER(
				SUBSTR(UUID,1,8) || '-' ||
				SUBSTR(UUID,9,4) || '-' ||
				SUBSTR(UUID,13,4) || '-' ||
				SUBSTR(UUID,17,4) || '-' ||
				SUBSTR(UUID,21)) 
			END AS UUID 
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.AJCORESTATUSCODE /* Remove update statement */
		WHERE STATUSCODETYPE ='ACCOUNT' AND CODE='INITIAL'
	) AS ACCOUNT_STATUS_UUID,
	CASE 
		WHEN aco.CONTINGENCY_FEE_SCHEDULE_ID IS NOT NULL THEN 
			LOWER(
			SUBSTR(aco.CONTINGENCY_FEE_SCHEDULE_ID,1,8) || '-' ||
			SUBSTR(aco.CONTINGENCY_FEE_SCHEDULE_ID,9,4) || '-' ||
			SUBSTR(aco.CONTINGENCY_FEE_SCHEDULE_ID,13,4) || '-' ||
			SUBSTR(aco.CONTINGENCY_FEE_SCHEDULE_ID,17,4) || '-' ||
			SUBSTR(aco.CONTINGENCY_FEE_SCHEDULE_ID,21)) 
	END AS COMMISSION_STRATEGY_UUID,
	etl_ai.ACCOUNTID AS MIG_SRC_ACCT_ID,
	0 AS IS_SUIT_FILED,
	0 AS IS_ON_JUDGMENT,
	0 AS IS_LEGAL_CASE_ACTIVE,
	0 AS INCLUDED_ON_BANKRUPTCY,
	92 AS WKFLOW_SCODE_ID,
	etl_ai.AFACINTHRUDT AS INTEREST_CURRENT_THRU,
	etl_ai.AFACINTRATE AS INTEREST_RATE,
	CASE 
		WHEN etl_ai.AFACINTRATE > 0 THEN 1
		ELSE 0
	END AS ASSESS_INTEREST	
FROM 
    ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_ACCOUNT_INFO etl_ai 
	INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNT acc ON acc.MIGRATION_SOURCE_ID = etl_ai.ACCOUNTID
	LEFT OUTER JOIN COM_FINVI_OASIS_CLIENTANDCREDITOR_{PP_TenantName}.AJ_CORE_ORGANIZATION aco ON acc.CLIENTCONTRACTID = aco.UUID