INSERT INTO COM_FINVI_OASIS_RESTRICTIONS_{PP_TenantName}.RESTRICTION_MAPPING
(
	ID,							
	COMMUNICATION_RESTRICTION_ID,
	TIME_ZONE_ID
)
SELECT
	SYS_GUID() AS ID,
	CM.ID  AS COMMUNICATION_RESTRICTION_ID,
	TV.ID  AS TIME_ZONE_ID
FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_RESTRICTION RS
	JOIN  COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER C ON RS.CONSUMER_ID =C.MIGRATION_SOURCE_ID
	JOIN COM_FINVI_OASIS_RESTRICTIONS_{PP_TenantName}.COMMUNICATION_RESTRICTION CM ON CM.CUSTOMER_ID=C.UUID
	JOIN ETL_OASIS_STG_LOAD_{PP_TenantName}.STATIC_TIMEZONE_VALUE tv  ON TV.DISPLAY_NAME  = RS.TIME_ZONE 
WHERE RS.TIME_ZONE IS NOT NULL